// ─────────────────────────────────────────────────────────────
// SPEC KEY CONTRACTS (enforced per category)
//
// smartphones → display | chip | battery | camera | storage
// laptops     → processor | ram | storage | display | battery
// audio       → battery | noiseCancellation | driverSize | connectivity | codec
// ─────────────────────────────────────────────────────────────

const specLabels = {
  smartphones: ["Display", "Chip", "Battery", "Camera", "Storage"],
  laptops: ["Processor", "RAM", "Storage", "Display", "Battery"],
  audio: ["Battery", "Noise Cancellation", "Driver Size", "Connectivity", "Codec"],
};

const products = [

  // ═══════════════════════════════════════════════
  // SMARTPHONES — 12 products
  // ═══════════════════════════════════════════════

  {
    id: "apple-iphone-15-pro",
    name: "iPhone 15 Pro",
    brand: "Apple",
    category: "smartphones",
    price: 134900,
    tag: "Best Seller",
    images: [
      "/images/apple-iphone-15-pro-1.png",
      "/images/apple-iphone-15-pro-2.png",
      "/images/apple-iphone-15-pro-3.png",
    ],
    description: "Titanium frame. A17 Pro chip. The benchmark everything else chases.",
    specs: {
      display: "6.1-inch Super Retina XDR OLED, 120Hz ProMotion",
      chip: "Apple A17 Pro",
      battery: "3274 mAh, 27W USB-C fast charging",
      camera: "48MP main + 12MP ultrawide + 12MP 3x telephoto",
      storage: "128GB / 256GB / 512GB / 1TB",
    },
    specLabels: specLabels.smartphones,
    variants: [
      { type: "color", value: "Natural Titanium" },
      { type: "color", value: "Black Titanium" },
      { type: "color", value: "White Titanium" },
      { type: "color", value: "Blue Titanium" },
      { type: "storage", value: "128GB", price: 134900 },
      { type: "storage", value: "256GB", price: 144900 },
      { type: "storage", value: "512GB", price: 164900 },
      { type: "storage", value: "1TB",   price: 184900 },
    ],
    rating: 4.9,
    isFeatured: true,
  },

  {
    id: "apple-iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    category: "smartphones",
    price: 159900,
    tag: "Pro",
    images: [
      "/images/apple-iphone-15-pro-max-1.png",
      "/images/apple-iphone-15-pro-max-2.png",
    ],
    description: "5x tetraprism telephoto. All-day titanium. Nothing left to want.",
    specs: {
      display: "6.7-inch Super Retina XDR OLED, 120Hz ProMotion",
      chip: "Apple A17 Pro",
      battery: "4422 mAh, 27W USB-C fast charging",
      camera: "48MP main + 12MP ultrawide + 12MP 5x tetraprism telephoto",
      storage: "256GB / 512GB / 1TB",
    },
    specLabels: specLabels.smartphones,
    variants: [
      { type: "color", value: "Natural Titanium" },
      { type: "color", value: "Black Titanium" },
      { type: "color", value: "White Titanium" },
      { type: "color", value: "Blue Titanium" },
      { type: "storage", value: "256GB", price: 159900 },
      { type: "storage", value: "512GB", price: 179900 },
      { type: "storage", value: "1TB",   price: 199900 },
    ],
    rating: 4.9,
    isFeatured: true,
  },

  {
    id: "samsung-galaxy-s24-ultra",
    name: "Galaxy S24 Ultra",
    brand: "Samsung",
    category: "smartphones",
    price: 129999,
    tag: "New",
    images: [
      "/images/samsung-galaxy-s24-ultra-1.png",
      "/images/samsung-galaxy-s24-ultra-2.png",
    ],
    description: "200MP intelligence. Built-in S Pen. Galaxy AI that actually works.",
    specs: {
      display: "6.8-inch Dynamic AMOLED 2X, 120Hz",
      chip: "Snapdragon 8 Gen 3",
      battery: "5000 mAh, 45W wired charging",
      camera: "200MP main + 12MP ultrawide + 50MP 5x periscope telephoto",
      storage: "256GB / 512GB / 1TB",
    },
    specLabels: specLabels.smartphones,
    variants: [
      { type: "color", value: "Titanium Black" },
      { type: "color", value: "Titanium Gray" },
      { type: "color", value: "Titanium Violet" },
      { type: "color", value: "Titanium Yellow" },
      { type: "storage", value: "256GB", price: 129999 },
      { type: "storage", value: "512GB", price: 149999 },
      { type: "storage", value: "1TB",   price: 169999 },
    ],
    rating: 4.8,
    isFeatured: false,
  },

  {
    id: "samsung-galaxy-s24-plus",
    name: "Galaxy S24+",
    brand: "Samsung",
    category: "smartphones",
    price: 99999,
    tag: "New",
    images: [
      "/images/samsung-galaxy-s24-plus-1.png",
      "/images/samsung-galaxy-s24-plus-2.png",
    ],
    description: "Flagship power in a refined flat-edge frame. Galaxy AI, no compromises.",
    specs: {
      display: "6.7-inch Dynamic AMOLED 2X, 120Hz",
      chip: "Snapdragon 8 Gen 3",
      battery: "4900 mAh, 45W wired charging",
      camera: "50MP main + 12MP ultrawide + 10MP 3x telephoto",
      storage: "256GB / 512GB",
    },
    specLabels: specLabels.smartphones,
    variants: [
      { type: "color", value: "Onyx Black" },
      { type: "color", value: "Marble Gray" },
      { type: "color", value: "Cobalt Violet" },
      { type: "storage", value: "256GB", price: 99999 },
      { type: "storage", value: "512GB", price: 119999 },
    ],
    rating: 4.7,
    isFeatured: false,
  },

  {
    id: "google-pixel-8-pro",
    name: "Pixel 8 Pro",
    brand: "Google",
    category: "smartphones",
    price: 106999,
    tag: "Pro",
    images: [
      "/images/google-pixel-8-pro-1.png",
      "/images/google-pixel-8-pro-2.png",
    ],
    description: "Seven years of updates. The sharpest Pixel camera. Pure Google, refined.",
    specs: {
      display: "6.7-inch LTPO OLED, 1–120Hz adaptive",
      chip: "Google Tensor G3",
      battery: "5050 mAh, 30W wired charging",
      camera: "50MP main + 48MP ultrawide + 48MP 5x telephoto",
      storage: "128GB / 256GB / 1TB",
    },
    specLabels: specLabels.smartphones,
    variants: [
      { type: "color", value: "Obsidian" },
      { type: "color", value: "Porcelain" },
      { type: "color", value: "Bay" },
      { type: "storage", value: "128GB", price: 106999 },
      { type: "storage", value: "256GB", price: 116999 },
      { type: "storage", value: "1TB",   price: 136999 },
    ],
    rating: 4.7,
    isFeatured: false,
  },

  {
    id: "google-pixel-8a",
    name: "Pixel 8a",
    brand: "Google",
    category: "smartphones",
    price: 52999,
    tag: "Best Seller",
    images: [
      "/images/google-pixel-8a-1.png",
      "/images/google-pixel-8a-2.png",
    ],
    description: "All the Pixel intelligence — in the form factor that fits every pocket.",
    specs: {
      display: "6.1-inch OLED, 120Hz",
      chip: "Google Tensor G3",
      battery: "4492 mAh, 18W wired charging",
      camera: "64MP main + 13MP ultrawide",
      storage: "128GB / 256GB",
    },
    specLabels: specLabels.smartphones,
    variants: [
      { type: "color", value: "Obsidian" },
      { type: "color", value: "Porcelain" },
      { type: "color", value: "Aloe" },
      { type: "color", value: "Bay" },
      { type: "storage", value: "128GB", price: 52999 },
      { type: "storage", value: "256GB", price: 62999 },
    ],
    rating: 4.6,
    isFeatured: false,
  },

  {
    id: "oneplus-12",
    name: "OnePlus 12",
    brand: "OnePlus",
    category: "smartphones",
    price: 64999,
    tag: "Best Seller",
    images: [
      "/images/oneplus-12-1.png",
      "/images/oneplus-12-2.png",
    ],
    description: "100W charging. Snapdragon 8 Gen 3. Speed is the only feature that matters.",
    specs: {
      display: "6.82-inch LTPO4 AMOLED, 1–120Hz adaptive",
      chip: "Snapdragon 8 Gen 3",
      battery: "5400 mAh, 100W wired + 50W wireless",
      camera: "50MP main + 48MP ultrawide + 64MP 3x telephoto",
      storage: "256GB / 512GB",
    },
    specLabels: specLabels.smartphones,
    variants: [
      { type: "color", value: "Silky Black" },
      { type: "color", value: "Flowy Emerald" },
      { type: "storage", value: "256GB", price: 64999 },
      { type: "storage", value: "512GB", price: 74999 },
    ],
    rating: 4.7,
    isFeatured: false,
  },

  {
    id: "xiaomi-14-ultra",
    name: "Xiaomi 14 Ultra",
    brand: "Xiaomi",
    category: "smartphones",
    price: 99999,
    tag: "Pro",
    images: [
      "/images/xiaomi-14-ultra-1.png",
      "/images/xiaomi-14-ultra-2.png",
    ],
    description: "Leica quad-camera. 1-inch sensor. A ceramic body built for imaging obsessives.",
    specs: {
      display: "6.73-inch LTPO AMOLED, 1–120Hz adaptive",
      chip: "Snapdragon 8 Gen 3",
      battery: "5000 mAh, 90W wired + 80W wireless",
      camera: "50MP (1-inch) + 50MP ultrawide + 50MP 3.2x + 50MP 5x (Leica)",
      storage: "256GB / 512GB",
    },
    specLabels: specLabels.smartphones,
    variants: [
      { type: "color", value: "Black" },
      { type: "color", value: "White" },
      { type: "storage", value: "256GB", price: 99999 },
      { type: "storage", value: "512GB", price: 114999 },
    ],
    rating: 4.8,
    isFeatured: false,
  },

  {
    id: "sony-xperia-1-vi",
    name: "Xperia 1 VI",
    brand: "Sony",
    category: "smartphones",
    price: 109990,
    tag: "Pro",
    images: [
      "/images/sony-xperia-1-vi-1.png",
      "/images/sony-xperia-1-vi-2.png",
    ],
    description: "4K HDR OLED. Variable optical zoom. Full manual control for serious creators.",
    specs: {
      display: "6.5-inch 4K HDR OLED, 120Hz",
      chip: "Snapdragon 8 Gen 3",
      battery: "5000 mAh, 30W wired charging",
      camera: "52MP main + 12MP ultrawide + 12MP 3.5–7.1x optical zoom",
      storage: "256GB / 512GB",
    },
    specLabels: specLabels.smartphones,
    variants: [
      { type: "color", value: "Black" },
      { type: "color", value: "Platinum Silver" },
      { type: "color", value: "Khaki Green" },
      { type: "storage", value: "256GB", price: 109990 },
      { type: "storage", value: "512GB", price: 129990 },
    ],
    rating: 4.6,
    isFeatured: false,
  },

  {
    id: "motorola-edge-50-pro",
    name: "Motorola Edge 50 Pro",
    brand: "Motorola",
    category: "smartphones",
    price: 31999,
    tag: "New",
    images: [
      "/images/motorola-edge-50-pro-1.png",
      "/images/motorola-edge-50-pro-2.png",
    ],
    description: "125W charging. Curved pOLED. Vegan leather that actually feels premium.",
    specs: {
      display: "6.7-inch pOLED, 144Hz",
      chip: "Snapdragon 7 Gen 3",
      battery: "4500 mAh, 125W wired + 50W wireless",
      camera: "50MP main + 13MP ultrawide + 10MP 3x telephoto",
      storage: "256GB",
    },
    specLabels: specLabels.smartphones,
    variants: [
      { type: "color", value: "Luxe Lavender" },
      { type: "color", value: "Black Beauty" },
      { type: "storage", value: "256GB", price: 31999 },
    ],
    rating: 4.5,
    isFeatured: false,
  },

  {
    id: "vivo-x100-pro",
    name: "vivo X100 Pro",
    brand: "vivo",
    category: "smartphones",
    price: 89999,
    tag: "Pro",
    images: [
      "/images/vivo-x100-pro-1.png",
      "/images/vivo-x100-pro-2.png",
    ],
    description: "Zeiss 1-inch sensor. Dimensity 9300. A new benchmark for mobile photography.",
    specs: {
      display: "6.78-inch LTPO AMOLED, 1–120Hz adaptive",
      chip: "MediaTek Dimensity 9300",
      battery: "5400 mAh, 100W wired + 50W wireless",
      camera: "50MP 1-inch main + 50MP ultrawide + 64MP 4.3x periscope (Zeiss)",
      storage: "256GB / 512GB",
    },
    specLabels: specLabels.smartphones,
    variants: [
      { type: "color", value: "Asteroid Black" },
      { type: "color", value: "Startrail Blue" },
      { type: "storage", value: "256GB", price: 89999 },
      { type: "storage", value: "512GB", price: 99999 },
    ],
    rating: 4.7,
    isFeatured: false,
  },

  {
    id: "nothing-phone-2a",
    name: "Nothing Phone (2a)",
    brand: "Nothing",
    category: "smartphones",
    price: 23999,
    tag: "New",
    images: [
      "/images/nothing-phone-2a-1.png",
      "/images/nothing-phone-2a-2.png",
    ],
    description: "Glyph Interface. Transparent back. Design-first in a world of identical slabs.",
    specs: {
      display: "6.7-inch AMOLED, 120Hz",
      chip: "MediaTek Dimensity 7200 Pro",
      battery: "5000 mAh, 45W wired charging",
      camera: "50MP main + 50MP ultrawide",
      storage: "128GB / 256GB",
    },
    specLabels: specLabels.smartphones,
    variants: [
      { type: "color", value: "Black" },
      { type: "color", value: "White" },
      { type: "color", value: "Blue" },
      { type: "storage", value: "128GB", price: 23999 },
      { type: "storage", value: "256GB", price: 27999 },
    ],
    rating: 4.5,
    isFeatured: false,
  },


  // ═══════════════════════════════════════════════
  // LAPTOPS — 12 products
  // ═══════════════════════════════════════════════

  {
    id: "apple-macbook-pro-14-m3-pro",
    name: "MacBook Pro 14\" M3 Pro",
    brand: "Apple",
    category: "laptops",
    price: 199900,
    tag: "Best Seller",
    images: [
      "/images/apple-macbook-pro-14-m3-pro-1.png",
      "/images/apple-macbook-pro-14-m3-pro-2.png",
    ],
    description: "Pro performance. Liquid Retina XDR. Built for work that can't wait.",
    specs: {
      processor: "Apple M3 Pro — 11-core CPU, 14-core GPU",
      ram: "18GB / 36GB unified memory",
      storage: "512GB / 1TB / 2TB SSD",
      display: "14.2-inch Liquid Retina XDR, 120Hz ProMotion",
      battery: "Up to 18 hours",
    },
    specLabels: specLabels.laptops,
    variants: [
      { type: "color", value: "Space Black" },
      { type: "color", value: "Silver" },
      { type: "ram", value: "18GB", price: 199900 },
      { type: "ram", value: "36GB", price: 239900 },
      { type: "storage", value: "512GB", price: 199900 },
      { type: "storage", value: "1TB",   price: 219900 },
      { type: "storage", value: "2TB",   price: 259900 },
    ],
    rating: 4.9,
    isFeatured: true,
  },

  {
    id: "apple-macbook-pro-16-m3-max",
    name: "MacBook Pro 16\" M3 Max",
    brand: "Apple",
    category: "laptops",
    price: 349900,
    tag: "Pro",
    images: [
      "/images/apple-macbook-pro-16-m3-max-1.png",
      "/images/apple-macbook-pro-16-m3-max-2.png",
    ],
    description: "M3 Max. Up to 128GB memory. The machine that renders, compiles and edits without breaking a sweat.",
    specs: {
      processor: "Apple M3 Max — 16-core CPU, 40-core GPU",
      ram: "48GB / 128GB unified memory",
      storage: "1TB / 2TB / 4TB SSD",
      display: "16.2-inch Liquid Retina XDR, 120Hz ProMotion",
      battery: "Up to 22 hours",
    },
    specLabels: specLabels.laptops,
    variants: [
      { type: "color", value: "Space Black" },
      { type: "color", value: "Silver" },
      { type: "ram", value: "48GB",  price: 349900 },
      { type: "ram", value: "128GB", price: 449900 },
      { type: "storage", value: "1TB", price: 349900 },
      { type: "storage", value: "2TB", price: 389900 },
      { type: "storage", value: "4TB", price: 449900 },
    ],
    rating: 4.9,
    isFeatured: false,
  },

  {
    id: "apple-macbook-air-15-m3",
    name: "MacBook Air 15\" M3",
    brand: "Apple",
    category: "laptops",
    price: 149900,
    tag: "Best Seller",
    images: [
      "/images/apple-macbook-air-15-m3-1.png",
      "/images/apple-macbook-air-15-m3-2.png",
    ],
    description: "Fanless. All-day. 15 inches of silence and speed.",
    specs: {
      processor: "Apple M3 — 8-core CPU, 10-core GPU",
      ram: "8GB / 16GB / 24GB unified memory",
      storage: "256GB / 512GB / 1TB / 2TB SSD",
      display: "15.3-inch Liquid Retina, 500 nits",
      battery: "Up to 18 hours",
    },
    specLabels: specLabels.laptops,
    variants: [
      { type: "color", value: "Midnight" },
      { type: "color", value: "Starlight" },
      { type: "color", value: "Space Gray" },
      { type: "color", value: "Sky Blue" },
      { type: "ram", value: "8GB",  price: 134900 },
      { type: "ram", value: "16GB", price: 149900 },
      { type: "ram", value: "24GB", price: 169900 },
      { type: "storage", value: "256GB", price: 134900 },
      { type: "storage", value: "512GB", price: 149900 },
      { type: "storage", value: "1TB",   price: 169900 },
    ],
    rating: 4.8,
    isFeatured: true,
  },

  {
    id: "dell-xps-15-9530",
    name: "Dell XPS 15 9530",
    brand: "Dell",
    category: "laptops",
    price: 179990,
    tag: "Pro",
    images: [
      "/images/dell-xps-15-9530-1.png",
      "/images/dell-xps-15-9530-2.png",
    ],
    description: "3.5K OLED. RTX 4070. CNC-aluminum built for the creative professional.",
    specs: {
      processor: "Intel Core i9-13900H",
      ram: "32GB / 64GB DDR5",
      storage: "1TB / 2TB NVMe SSD",
      display: "15.6-inch 3.5K OLED touch, 60Hz",
      battery: "86Wh, up to 13 hours",
    },
    specLabels: specLabels.laptops,
    variants: [
      { type: "color", value: "Platinum Silver" },
      { type: "color", value: "Graphite" },
      { type: "ram", value: "32GB", price: 179990 },
      { type: "ram", value: "64GB", price: 219990 },
      { type: "storage", value: "1TB", price: 179990 },
      { type: "storage", value: "2TB", price: 209990 },
    ],
    rating: 4.7,
    isFeatured: false,
  },

  {
    id: "dell-xps-13-plus",
    name: "Dell XPS 13 Plus",
    brand: "Dell",
    category: "laptops",
    price: 139990,
    tag: "New",
    images: [
      "/images/dell-xps-13-plus-1.png",
      "/images/dell-xps-13-plus-2.png",
    ],
    description: "Zero-lattice keyboard. OLED touch. Intel Evo certified in a 13.4-inch form.",
    specs: {
      processor: "Intel Core i7-1360P",
      ram: "16GB / 32GB LPDDR5",
      storage: "512GB / 1TB NVMe SSD",
      display: "13.4-inch OLED touch, 60Hz",
      battery: "55Wh, up to 12 hours",
    },
    specLabels: specLabels.laptops,
    variants: [
      { type: "color", value: "Platinum" },
      { type: "color", value: "Graphite" },
      { type: "ram", value: "16GB", price: 139990 },
      { type: "ram", value: "32GB", price: 159990 },
      { type: "storage", value: "512GB", price: 139990 },
      { type: "storage", value: "1TB",   price: 159990 },
    ],
    rating: 4.6,
    isFeatured: false,
  },

  {
    id: "lg-gram-16-2024",
    name: "LG gram 16 (2024)",
    brand: "LG",
    category: "laptops",
    price: 119990,
    tag: "New",
    images: [
      "/images/lg-gram-16-2024-1.png",
      "/images/lg-gram-16-2024-2.png",
    ],
    description: "1.19 kg. 22-hour battery. The lightest 16-inch laptop worth buying.",
    specs: {
      processor: "Intel Core Ultra 7 155H",
      ram: "16GB / 32GB LPDDR5",
      storage: "512GB / 1TB NVMe SSD",
      display: "16-inch WQXGA IPS, 144Hz",
      battery: "99Wh, up to 22 hours",
    },
    specLabels: specLabels.laptops,
    variants: [
      { type: "color", value: "White" },
      { type: "color", value: "Obsidian Black" },
      { type: "ram", value: "16GB", price: 119990 },
      { type: "ram", value: "32GB", price: 139990 },
      { type: "storage", value: "512GB", price: 119990 },
      { type: "storage", value: "1TB",   price: 134990 },
    ],
    rating: 4.6,
    isFeatured: false,
  },

  {
    id: "asus-zenbook-14-oled",
    name: "ASUS Zenbook 14 OLED",
    brand: "ASUS",
    category: "laptops",
    price: 89990,
    tag: "Best Seller",
    images: [
      "/images/asus-zenbook-14-oled-1.png",
      "/images/asus-zenbook-14-oled-2.png",
    ],
    description: "2.8K OLED. Ryzen 7. Under 1.4 kg. Everyday excellence, no exceptions.",
    specs: {
      processor: "AMD Ryzen 7 7745HX",
      ram: "16GB / 32GB LPDDR5",
      storage: "512GB / 1TB NVMe SSD",
      display: "14-inch 2.8K OLED, 120Hz",
      battery: "75Wh, up to 15 hours",
    },
    specLabels: specLabels.laptops,
    variants: [
      { type: "color", value: "Ponder Blue" },
      { type: "color", value: "Basalt Gray" },
      { type: "ram", value: "16GB", price: 89990 },
      { type: "ram", value: "32GB", price: 109990 },
      { type: "storage", value: "512GB", price: 89990 },
      { type: "storage", value: "1TB",   price: 104990 },
    ],
    rating: 4.7,
    isFeatured: false,
  },

  {
    id: "asus-rog-zephyrus-g14-2024",
    name: "ASUS ROG Zephyrus G14 (2024)",
    brand: "ASUS",
    category: "laptops",
    price: 169990,
    tag: "Pro",
    images: [
      "/images/asus-rog-zephyrus-g14-1.png",
      "/images/asus-rog-zephyrus-g14-2.png",
    ],
    description: "Ryzen 9. RX 7900S. A 14-inch gaming powerhouse that fits in any bag.",
    specs: {
      processor: "AMD Ryzen 9 8945HS",
      ram: "32GB DDR5",
      storage: "1TB NVMe SSD",
      display: "14-inch 2.5K OLED, 165Hz",
      battery: "73Wh, up to 10 hours",
    },
    specLabels: specLabels.laptops,
    variants: [
      { type: "color", value: "Eclipse Gray" },
      { type: "color", value: "Platinum White" },
      { type: "ram", value: "32GB", price: 169990 },
      { type: "storage", value: "1TB", price: 169990 },
    ],
    rating: 4.8,
    isFeatured: false,
  },

  {
    id: "microsoft-surface-laptop-6",
    name: "Microsoft Surface Laptop 6",
    brand: "Microsoft",
    category: "laptops",
    price: 139999,
    tag: "New",
    images: [
      "/images/microsoft-surface-laptop-6-1.png",
      "/images/microsoft-surface-laptop-6-2.png",
    ],
    description: "PixelSense touch. Copilot+ AI built in. Microsoft's most refined laptop yet.",
    specs: {
      processor: "Intel Core Ultra 7 165H",
      ram: "16GB / 32GB / 64GB LPDDR5x",
      storage: "512GB / 1TB NVMe SSD",
      display: "15-inch PixelSense touch, 2496×1664, 60Hz",
      battery: "Up to 22 hours",
    },
    specLabels: specLabels.laptops,
    variants: [
      { type: "color", value: "Platinum" },
      { type: "color", value: "Black" },
      { type: "color", value: "Sapphire" },
      { type: "ram", value: "16GB", price: 119999 },
      { type: "ram", value: "32GB", price: 139999 },
      { type: "ram", value: "64GB", price: 169999 },
      { type: "storage", value: "512GB", price: 139999 },
      { type: "storage", value: "1TB",   price: 159999 },
    ],
    rating: 4.6,
    isFeatured: false,
  },

  {
    id: "hp-spectre-x360-14",
    name: "HP Spectre x360 14",
    brand: "HP",
    category: "laptops",
    price: 149990,
    tag: "Pro",
    images: [
      "/images/hp-spectre-x360-14-1.png",
      "/images/hp-spectre-x360-14-2.png",
    ],
    description: "2-in-1 convertible. 2.8K OLED touch. Gem-cut design that turns heads.",
    specs: {
      processor: "Intel Core Ultra 7 155U",
      ram: "16GB / 32GB LPDDR5",
      storage: "512GB / 1TB / 2TB NVMe SSD",
      display: "14-inch 2.8K OLED touch, 120Hz",
      battery: "66Wh, up to 17 hours",
    },
    specLabels: specLabels.laptops,
    variants: [
      { type: "color", value: "Nightfall Black" },
      { type: "color", value: "Natural Silver" },
      { type: "ram", value: "16GB", price: 134990 },
      { type: "ram", value: "32GB", price: 149990 },
      { type: "storage", value: "512GB", price: 149990 },
      { type: "storage", value: "1TB",   price: 169990 },
    ],
    rating: 4.7,
    isFeatured: false,
  },

  {
    id: "lenovo-thinkpad-x1-carbon-g12",
    name: "Lenovo ThinkPad X1 Carbon Gen 12",
    brand: "Lenovo",
    category: "laptops",
    price: 159990,
    tag: "Pro",
    images: [
      "/images/lenovo-thinkpad-x1-carbon-g12-1.png",
      "/images/lenovo-thinkpad-x1-carbon-g12-2.png",
    ],
    description: "Under 1.1 kg. Military-grade. Intel vPro built for people who can't afford downtime.",
    specs: {
      processor: "Intel Core Ultra 7 164U",
      ram: "16GB / 32GB / 64GB LPDDR5x",
      storage: "512GB / 1TB / 2TB NVMe SSD",
      display: "14-inch 2.8K IPS, 120Hz",
      battery: "57Wh, up to 15 hours",
    },
    specLabels: specLabels.laptops,
    variants: [
      { type: "color", value: "Deep Black" },
      { type: "ram", value: "16GB", price: 139990 },
      { type: "ram", value: "32GB", price: 159990 },
      { type: "ram", value: "64GB", price: 199990 },
      { type: "storage", value: "512GB", price: 159990 },
      { type: "storage", value: "1TB",   price: 179990 },
    ],
    rating: 4.7,
    isFeatured: false,
  },

  {
    id: "razer-blade-15-2024",
    name: "Razer Blade 15 (2024)",
    brand: "Razer",
    category: "laptops",
    price: 219990,
    tag: "Pro",
    images: [
      "/images/razer-blade-15-2024-1.png",
      "/images/razer-blade-15-2024-2.png",
    ],
    description: "RTX 4080. 240Hz QHD+ OLED. CNC-aluminum thinner than most ultrabooks.",
    specs: {
      processor: "Intel Core i9-14900HX",
      ram: "32GB / 64GB DDR5",
      storage: "1TB / 2TB NVMe SSD",
      display: "15.6-inch QHD+ OLED, 240Hz",
      battery: "80Wh, up to 8 hours",
    },
    specLabels: specLabels.laptops,
    variants: [
      { type: "color", value: "Matte Black" },
      { type: "ram", value: "32GB", price: 219990 },
      { type: "ram", value: "64GB", price: 259990 },
      { type: "storage", value: "1TB", price: 219990 },
      { type: "storage", value: "2TB", price: 249990 },
    ],
    rating: 4.8,
    isFeatured: false,
  },


  // ═══════════════════════════════════════════════
  // AUDIO — 12 products
  // ═══════════════════════════════════════════════

  {
    id: "sony-wh-1000xm5",
    name: "Sony WH-1000XM5",
    brand: "Sony",
    category: "audio",
    price: 28990,
    tag: "Best Seller",
    images: [
      "/images/sony-wh-1000xm5-1.png",
      "/images/sony-wh-1000xm5-2.png",
    ],
    description: "Eight microphones. 30-hour battery. The ANC benchmark for over-ear headphones.",
    specs: {
      battery: "30 hours (ANC on) — 3 min charge = 3 hours",
      noiseCancellation: "Dual Noise Sensor — 8 microphones",
      driverSize: "30mm",
      connectivity: "Bluetooth 5.2, multipoint (2 devices)",
      codec: "LDAC, AAC, SBC",
    },
    specLabels: specLabels.audio,
    variants: [
      { type: "color", value: "Midnight Black" },
      { type: "color", value: "Platinum Silver" },
    ],
    rating: 4.9,
    isFeatured: true,
  },

  {
    id: "sony-wf-1000xm5",
    name: "Sony WF-1000XM5",
    brand: "Sony",
    category: "audio",
    price: 19990,
    tag: "Best Seller",
    images: [
      "/images/sony-wf-1000xm5-1.png",
      "/images/sony-wf-1000xm5-2.png",
    ],
    description: "The smallest Sony flagship. LDAC wireless. ANC that outpunches its size.",
    specs: {
      battery: "8 hours bud (36 hours with case)",
      noiseCancellation: "Dual Noise Sensor — 4 microphones",
      driverSize: "8.4mm",
      connectivity: "Bluetooth 5.3, multipoint",
      codec: "LDAC, AAC, SBC",
    },
    specLabels: specLabels.audio,
    variants: [
      { type: "color", value: "Black" },
      { type: "color", value: "Platinum Silver" },
    ],
    rating: 4.8,
    isFeatured: false,
  },

  {
    id: "apple-airpods-pro-2",
    name: "Apple AirPods Pro (2nd Gen)",
    brand: "Apple",
    category: "audio",
    price: 24900,
    tag: "Best Seller",
    images: [
      "/images/apple-airpods-pro-2-1.png",
      "/images/apple-airpods-pro-2-2.png",
    ],
    description: "H2 chip. Adaptive Audio. Sound that adjusts to your world in real time.",
    specs: {
      battery: "6 hours bud (30 hours with case)",
      noiseCancellation: "Adaptive ANC + Transparency mode",
      driverSize: "Custom Apple driver",
      connectivity: "Bluetooth 5.3, seamless Apple ecosystem",
      codec: "AAC, SBC",
    },
    specLabels: specLabels.audio,
    variants: [
      { type: "color", value: "White" },
    ],
    rating: 4.8,
    isFeatured: false,
  },

  {
    id: "apple-airpods-max-usbc",
    name: "Apple AirPods Max (USB-C)",
    brand: "Apple",
    category: "audio",
    price: 59900,
    tag: "Pro",
    images: [
      "/images/apple-airpods-max-usbc-1.png",
      "/images/apple-airpods-max-usbc-2.png",
    ],
    description: "Computational audio. Dynamic head tracking. Over-ear sound reimagined by Apple.",
    specs: {
      battery: "20 hours (ANC + Spatial Audio on)",
      noiseCancellation: "Active Noise Cancellation + Transparency mode",
      driverSize: "40mm Apple custom",
      connectivity: "Bluetooth 5.0, Apple ecosystem",
      codec: "AAC, SBC",
    },
    specLabels: specLabels.audio,
    variants: [
      { type: "color", value: "Midnight" },
      { type: "color", value: "Starlight" },
      { type: "color", value: "Sky Blue" },
      { type: "color", value: "Orange" },
      { type: "color", value: "Purple" },
    ],
    rating: 4.7,
    isFeatured: false,
  },

  {
    id: "bose-quietcomfort-45",
    name: "Bose QuietComfort 45",
    brand: "Bose",
    category: "audio",
    price: 26990,
    tag: "Best Seller",
    images: [
      "/images/bose-quietcomfort-45-1.png",
      "/images/bose-quietcomfort-45-2.png",
    ],
    description: "24 hours. Deep balanced sound. The definition of all-day wearability.",
    specs: {
      battery: "24 hours (ANC on) — 15 min charge = 3 hours",
      noiseCancellation: "Bose Quiet Mode + Aware Mode",
      driverSize: "40mm",
      connectivity: "Bluetooth 5.1, multipoint",
      codec: "AAC, SBC",
    },
    specLabels: specLabels.audio,
    variants: [
      { type: "color", value: "Triple Black" },
      { type: "color", value: "White Smoke" },
    ],
    rating: 4.7,
    isFeatured: false,
  },

  {
    id: "bose-qc-ultra-earbuds",
    name: "Bose QuietComfort Ultra Earbuds",
    brand: "Bose",
    category: "audio",
    price: 23990,
    tag: "New",
    images: [
      "/images/bose-qc-ultra-earbuds-1.png",
      "/images/bose-qc-ultra-earbuds-2.png",
    ],
    description: "CustomTune. Immersive Audio. Earbuds that learn the shape of your ears.",
    specs: {
      battery: "6 hours bud (24 hours with case)",
      noiseCancellation: "CustomTune ANC + Immersive Audio mode",
      driverSize: "9.3mm",
      connectivity: "Bluetooth 5.3, multipoint",
      codec: "AAC, SBC",
    },
    specLabels: specLabels.audio,
    variants: [
      { type: "color", value: "Black" },
      { type: "color", value: "White" },
      { type: "color", value: "Moonstone Blue" },
    ],
    rating: 4.7,
    isFeatured: false,
  },

  {
    id: "samsung-galaxy-buds3-pro",
    name: "Samsung Galaxy Buds3 Pro",
    brand: "Samsung",
    category: "audio",
    price: 17999,
    tag: "New",
    images: [
      "/images/samsung-galaxy-buds3-pro-1.png",
      "/images/samsung-galaxy-buds3-pro-2.png",
    ],
    description: "Blade-tip design. AI ANC. Built for those deep in the Galaxy ecosystem.",
    specs: {
      battery: "6 hours bud (30 hours with case)",
      noiseCancellation: "Intelligent ANC — 3-mic array",
      driverSize: "10.5mm woofer + 6.1mm tweeter",
      connectivity: "Bluetooth 5.4, LE Audio",
      codec: "SSC, AAC, SBC",
    },
    specLabels: specLabels.audio,
    variants: [
      { type: "color", value: "White" },
      { type: "color", value: "Silver" },
    ],
    rating: 4.6,
    isFeatured: false,
  },

  {
    id: "sennheiser-momentum-4",
    name: "Sennheiser Momentum 4 Wireless",
    brand: "Sennheiser",
    category: "audio",
    price: 29990,
    tag: "Pro",
    images: [
      "/images/sennheiser-momentum-4-1.png",
      "/images/sennheiser-momentum-4-2.png",
    ],
    description: "60-hour battery. Audiophile tuning. ANC that doesn't color the sound.",
    specs: {
      battery: "60 hours (ANC on)",
      noiseCancellation: "Adaptive ANC + Transparency mode",
      driverSize: "42mm",
      connectivity: "Bluetooth 5.2, multipoint",
      codec: "aptX Adaptive, AAC, SBC",
    },
    specLabels: specLabels.audio,
    variants: [
      { type: "color", value: "Black" },
      { type: "color", value: "White" },
      { type: "color", value: "Denim" },
    ],
    rating: 4.8,
    isFeatured: false,
  },

  {
    id: "jabra-evolve2-85",
    name: "Jabra Evolve2 85",
    brand: "Jabra",
    category: "audio",
    price: 34990,
    tag: "Pro",
    images: [
      "/images/jabra-evolve2-85-1.png",
      "/images/jabra-evolve2-85-2.png",
    ],
    description: "10 microphones. 37-hour battery. Enterprise call quality without compromise.",
    specs: {
      battery: "37 hours (ANC on)",
      noiseCancellation: "Advanced Hybrid ANC — 6 mics for calls",
      driverSize: "40mm",
      connectivity: "Bluetooth 5.0 + USB-A/C dongle",
      codec: "aptX Adaptive, AAC, SBC",
    },
    specLabels: specLabels.audio,
    variants: [
      { type: "color", value: "Black" },
      { type: "color", value: "Beige" },
    ],
    rating: 4.6,
    isFeatured: false,
  },

  {
    id: "marshall-monitor-3-anc",
    name: "Marshall Monitor III ANC",
    brand: "Marshall",
    category: "audio",
    price: 22999,
    tag: "New",
    images: [
      "/images/marshall-monitor-3-anc-1.png",
      "/images/marshall-monitor-3-anc-2.png",
    ],
    description: "Rock-tuned drivers. Hybrid ANC. Vintage aesthetic with nothing vintage about the sound.",
    specs: {
      battery: "30 hours (ANC on)",
      noiseCancellation: "Hybrid ANC",
      driverSize: "40mm",
      connectivity: "Bluetooth 5.2, multipoint",
      codec: "aptX HD, AAC, SBC",
    },
    specLabels: specLabels.audio,
    variants: [
      { type: "color", value: "Black" },
      { type: "color", value: "Brown" },
    ],
    rating: 4.6,
    isFeatured: false,
  },

  {
    id: "anker-soundcore-q45",
    name: "Anker Soundcore Q45",
    brand: "Anker",
    category: "audio",
    price: 5999,
    tag: "Best Seller",
    images: [
      "/images/anker-soundcore-q45-1.png",
      "/images/anker-soundcore-q45-2.png",
    ],
    description: "50-hour battery. LDAC. Adaptive ANC at a price that challenges every competitor above it.",
    specs: {
      battery: "50 hours (ANC on)",
      noiseCancellation: "Adaptive Hybrid ANC",
      driverSize: "40mm",
      connectivity: "Bluetooth 5.3, multipoint",
      codec: "LDAC, AAC, SBC",
    },
    specLabels: specLabels.audio,
    variants: [
      { type: "color", value: "Black" },
      { type: "color", value: "White" },
    ],
    rating: 4.5,
    isFeatured: false,
  },

  {
    id: "nothing-ear-2",
    name: "Nothing Ear (2)",
    brand: "Nothing",
    category: "audio",
    price: 9999,
    tag: "New",
    images: [
      "/images/nothing-ear-2-1.png",
      "/images/nothing-ear-2-2.png",
    ],
    description: "Transparent. Dual-chamber. LHDC 5.0 wireless. Nothing to hide, everything to hear.",
    specs: {
      battery: "6.3 hours bud (36 hours with case)",
      noiseCancellation: "Active Noise Cancellation + Transparency mode",
      driverSize: "11.6mm",
      connectivity: "Bluetooth 5.3, multipoint",
      codec: "LHDC 5.0, AAC, SBC",
    },
    specLabels: specLabels.audio,
    variants: [
      { type: "color", value: "White" },
      { type: "color", value: "Black" },
    ],
    rating: 4.6,
    isFeatured: false,
  },

];

export { specLabels };
export default products;
